<?php
/**
 * Plugin Name:       Truffle Box
 * Plugin URI:        http://septianfujianto.com/truffle-box/
 * Description:       Simple portable functionality plugin.
 * Version:           1.0.1
 * Author:            Septian Ahmad Fujianto
 * Author URI:        http://septianfujianto.com/
 * License:           GPL-2.0+
 * License URI:       http://www.gnu.org/licenses/gpl-2.0.txt
 * Text Domain:       truffle-box
 * Domain Path:       /languages
 * Bitbucket Plugin URI: https://bitbucket.org/zucharest/truffle-box
 * Bitbucket Branch: master
 */

/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function trufflebox_project_detail_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function trufflebox_project_detail_add_meta_box() {
	add_meta_box(
		'trufflebox_project_detail-project-detail',
		__( 'Project Detail', 'trufflebox' ),
		'trufflebox_project_detail_html',
		'jetpack-portfolio',
		'normal',
		'high'
	);
}

add_action( 'add_meta_boxes', 'trufflebox_project_detail_add_meta_box' );

/* Register all metabox to tpf-themes rest api */
add_action( 'rest_api_init', 'trufflebox_register_metabox_rest');

function trufflebox_register_metabox_rest() {
	function trufflebox_get_all_post_meta($post) {
			$meta = get_post_meta($post['id']);
			$current_meta = get_post_meta($post['id']);
			$meta_data = [];

			foreach($current_meta as $key => $obj){
				$meta_data[$key] = $obj[0];
			}
			
			return $meta_data;
		}

    register_rest_field( 'jetpack-portfolio', 'post_meta', array(
				'show_in_rest' => true,
        'get_callback' => 'trufflebox_get_all_post_meta',
    ));
}

function trufflebox_project_detail_html( $post) {
	wp_nonce_field( '_trufflebox_project_detail_nonce', 'trufflebox_project_detail_nonce' ); ?>

	<p>
		<label for="trufflebox_project_detail_project_desc"><?php _e( 'Description', 'trufflebox' ); ?></label><br>
		<?php wp_editor(trufflebox_project_detail_get_meta( 'trufflebox_project_detail_project_desc' ), 'trufflebox_project_detail_project_desc', array('textarea_rows' => '5')); ?>
		
	</p>

	<p>
		<label for="trufflebox_project_detail_project_url"><?php _e( 'URL', 'trufflebox' ); ?></label><br>
		<input type="text" name="trufflebox_project_detail_project_url" id="trufflebox_project_detail_project_url" class="large-text" value="<?php echo trufflebox_project_detail_get_meta( 'trufflebox_project_detail_project_url' ); ?>">
	</p>	
	<p>
		<label for="trufflebox_project_detail_date_completion"><?php _e( 'Time Completion', 'trufflebox' ); ?></label><br>
		<input type="date" name="trufflebox_project_detail_date_completion" id="trufflebox_project_detail_date_completion" class="large-text" value="<?php echo date('Y-m-d', trufflebox_project_detail_get_meta( 'trufflebox_project_detail_date_completion' )); ?>">
	</p><?php
}

function trufflebox_project_detail_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;

	if ( ! isset( $_POST['trufflebox_project_detail_nonce'] ) || ! wp_verify_nonce( $_POST['trufflebox_project_detail_nonce'], '_trufflebox_project_detail_nonce' ) ) return;

	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['trufflebox_project_detail_project_desc'] ) )
		update_post_meta( $post_id, 'trufflebox_project_detail_project_desc', esc_attr( $_POST['trufflebox_project_detail_project_desc'] ) );

	if ( isset( $_POST['trufflebox_project_detail_project_url'] ) )
		update_post_meta( $post_id, 'trufflebox_project_detail_project_url', esc_attr( $_POST['trufflebox_project_detail_project_url'] ) );

	if ( isset( $_POST['trufflebox_project_detail_date_completion'] ) )
		update_post_meta( $post_id, 'trufflebox_project_detail_date_completion', esc_attr(strtotime($_POST['trufflebox_project_detail_date_completion'])) );
}

add_action( 'save_post', 'trufflebox_project_detail_save' );

/*
	Usage: trufflebox_project_detail_get_meta( 'trufflebox_project_detail_project_url' )
	Usage: trufflebox_project_detail_get_meta( 'trufflebox_project_detail_date_completion' )
*/